version: 2
jobs:
  build:
    working_directory: ~/MymTanzania
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - build:
          name: npm build
          command: npm run build

workflows:
  version: 2
  jobs:
    - build
    - deploy_master:
        name: Deploy site
        command: aws s3 sync build s3://www.mymtanzania.se/ --region eu-central-1 --delete
        filters:
          branches:
            only: master
    - deploy_develop:
        name: Deploy development site
        command: aws s3 sync build s3://$DEVELOP_BUCKET/ --region eu-central-1 --delete
        filters:
          branches:
            only: develop
