version: 2
jobs:
  build:
    working_directory: ~/MymTanzania
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - run:
          name: Install aws cli
          command: |
            sudo apt-get -y -qq update
            sudo apt-get -y -qq install python3.4-dev
            curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python3.4 get-pip.py --user
            sudo pip install awscli --upgrade --user
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: npm build
          command: npm run build
      - run:
          name: Deploy site
          command: aws s3 sync build s3://www.mymtanzania.se/ --region eu-central-1 --delete
          filters:
            branches:
              only: master
      - run:
          name: Deploy development site
          command: aws s3 sync build s3://$DEVELOP_BUCKET/ --region eu-central-1 --delete
          filters:
            branches:
              only: develop
